name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make project
      run: make

    - name: make directory
      run: mkdir -p files

    - name: Create file
      run: echo hs-dvr-telnet > files/backdoor.bin
            
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
          name: my-file
          path: files/backdoor.bin        
